project:
  type: website
  output-dir: _site

website:
  title: "CAUSE Digest"
  description: "Semester updates from the Consortium for the Advancement of Undergraduate Statistics Education"
  favicon: assets\favicon.ico

  navbar:
    right:
      - text: Home
        href: index.qmd
      - text: Go to CAUSEweb
        href: https://www.causeweb.org/cause

  page-footer:
    left: |
      &copy; 2026 CAUSE<br>
      Consortium for the Advancement of Undergraduate Statistics Education
    right: |
      <a href="mailto:L-STAT-CAUSEweb-subscribe-request@lists.psu.edu?subject=Subscribe%20Request&body=Subscribe%20Request">Join the CAUSE eNews List</a><br>
      <a href="https://causeweb.org/slack">Join us on Slack</a><br>
      <a href="https://www.causeweb.org/cause">Go to CAUSEweb</a>

format:
  html:
    theme:
      - flatly
      - theme.scss
    mainfont: Raleway
    toc: true
    toc-depth: 3
    page-layout: article
    grid:
      body-width: 700px   # Narrow, editorial width
      gutter-width: 1.2rem




